---
title: My Resume
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://harssh.github.io
baseurl: "/"
description: Harssh S Shrivastava Full Stack Ruby On Rails developer.
theme_skin: blue
chrome_mobile_color: 
analytics: UA-138598737-1
sass:
  sass_dir: _sass
  style: compressed
compress-site: true
encoding: utf-8
compress_html:
  clippings: all
  ignore:
    envs: development
port: 4000
host: 0.0.0.0
safe: false
sidebar:
  about: true
  education: true
  name: Harssh S Shrivastava
  tagline: Full Stack Developer/ Ruby ON Rails Engineer
  avatar: profile.jpeg
  email: harssh122@gmail.com
  phone: 763 283 8442
  website: github.com/harssh
  linkedin: harssh
  github: harssh
  gitlab: 
  bitbucket: 
  twitter: "@IamStackDev"
  stack-overflow: 1863010/magnum
  codewars: 
  goodreads: 
  languages:
  - idiom: English
    level: Professional
career-profile:
  title: Career Profile
  summary: "Full Stack Developer/ Ruby On Rails Engineer with 7+ years experience
    developing robust code for high-volume businesses and startups. Experienced in
    E-Commerce, healthcare compensation, analytics and survey based products. Increased
    code-efficiency and upgrades for multiple businesses. An enthusiast for open source
    and team player. \nKeen to have feature ownership."
education:
- degree: BE in Information Technology
  university: University of Pune
  time: 2008 - 2012
  details: |
    Describe your study here lorem ipsum dolor sit amet, consectetuer
    adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum
    sociis natoque penatibus et magnis dis parturient montes, nascetur
    ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu,
    pretium quis, sem.

      - Bullet point
      - Bullet point
experiences:
- role: Software Engineer/Ruby On Rails developer
  time: 2015 - Present
  company: Sullivan Cotter, Minneapolis
  details: "Modify existing software to correct errors, to adapt it to new hardware,
    or to upgrade interfaces and improve performance.\nAnalyze information to determine,
    recommend, and plan installation of a new system or modification of an existing
    system.\nVerify stability, interoperability, portability, security, or scalability
    of system architecture.\nReview code  and own complete production and UAT deployment
    cycle.\nOwn feature requirement and end to end development.\nRefactored legacy
    code, upgrade. Implement CI/build systems.\nManage and develop multi portal sign
    on API.\nDevelop data endpoint APIS for other applications.\nManage security and
    access to AWS EC2 and Database RDS instances.\nTechnologies: Ruby, Ruby on Rails,
    JavaScript, CSS,Travis-Ci, HTML, Rack, Capistrano, Cucumber, Rspec,  Mysql, Airbrake,
    Jquery. "
- role: Senior Software Engineer
  time: 2014 - 2015
  company: Google, London
  details: |
    Describe your role here lorem ipsum dolor sit amet, consectetuer
    adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
    Cum sociis natoque penatibus et magnis dis parturient montes,
    nascetur ridiculus mus. Donec quam felis, ultricies nec,
    pellentesque eu, pretium quis, sem.

      - Bullet point
      - Bullet point
- role: UI Developer
  time: 2012 - 2014
  company: Amazon, London
  details: |
    Describe your role here lorem ipsum dolor sit amet, consectetuer
    adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
    Cum sociis natoque penatibus et magnis dis parturient montes,
    nascetur ridiculus mus. Donec quam felis, ultricies nec,
    pellentesque eu, pretium quis, sem.

      - Bullet point
      - Bullet point
projects:
  title: Projects
  intro: 'You can list your side projects or open source libraries in this section.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula
    in nunc bibendum fringilla a eu lectus.

'
  assignments:
  - title: Velocity
    link: "#hook"
    tagline: A responsive website template designed to help startups promote, market
      and sell their products.
  - title: DevStudio
    link: "#"
    tagline: A responsive website template designed to help web developers/designers
      market their services.
  - title: Tempo
    link: "#"
    tagline: A responsive website template designed to help startups promote their
      products or services and to attract users &amp; investors
  - title: Atom
    link: "#"
    tagline: A comprehensive website template solution for startups/developers to
      market their mobile apps.
  - title: Delta
    link: "#"
    tagline: A responsive Bootstrap one page theme designed to help app developers
      promote their mobile apps
publications:
  title: 
  intro: 
  papers:
  - title: 
    authors: 
    conference: 
  - title: 
    authors: 
    conference: 
  - title: 
    authors: 
    conference: 
skills:
  title: Skills &amp; Proficiency
  toolset:
  - name: 'Ruby On Rails '
    level: 98%
  - name: Javascript & jQuery
    level: 98%
  - name: Ruby
    level: 98%
  - name: HTML5 & CSS
    level: 95%
  - name: AWS
    level: 85%
  - name: Redis
    level: 60%
footer: 'Designed by <a href="http://themes.3rdwavemedia.com" target="_blank" rel="nofollow">Xiaoying
  Riley</a>

'
