---
title: My Resume
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://harssh.github.io
baseurl: "/"
description: A beautiful Jekyll theme for creating resume
theme_skin: blue
chrome_mobile_color: 
analytics: UA-83979
sass:
  sass_dir: _sass
  style: compressed
compress-site: true
encoding: utf-8
compress_html:
  clippings: all
  ignore:
    envs: development
port: 4000
host: 0.0.0.0
safe: false
