---
title: Jekyll Bootstrap
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:year/:month/:day/:title"
exclude:
- ".rvmrc"
- ".rbenv-version"
- README.md
- Rakefile
- changelog.md
pygments: true
tagline: Site Tagline
author:
  name: Harssh S Shrivastava
  email: harssh122@gmail.com
  github: harsshhfs
  twitter: harssh219
production_url: http://username.github.io
JB:
  version: 0.3.0
  BASE_PATH: false
  ASSET_PATH: false
  archive_path: "/archive.html"
  categories_path: "/categories.html"
  tags_path: "/tags.html"
  atom_path: "/atom.xml"
  rss_path: "/rss.xml"
  comments:
    provider: disqus
    disqus:
      short_name: jekyllbootstrap
    livefyre:
      site_id: 123
    intensedebate:
      account: 123abc
    facebook:
      appid: 123
      num_posts: 5
      width: 580
      colorscheme: light
  analytics:
    provider: google
    google:
      tracking_id: UA-123-12
    getclicky:
      site_id: 
    mixpanel:
      token: _MIXPANEL_TOKEN_
    piwik:
      baseURL: myserver.tld/piwik
      idsite: '1'
  sharing:
    provider: false
