---
title: Portfolio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: by Harssh S Shrivastava
email: harssh122@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under
  the Creative Commons.
url: 
author:
  name: Harssh S Shrivastava
  email: harssh122@gmail.com
  github: harssh
  twitter: IamStackDev
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: "(716) 555-5555"
tiles-source: pages
tiles-count: 6
500px_url: 
facebook_url: 
github_url: 
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/harssh
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/IamStackDev
markdown: kramdown
sass:
  style: compressed
permalink: "/:categories/:year/:month/:day/:title"
exclude:
- ".rvmrc"
- ".rbenv-version"
- README.md
- Rakefile
- changelog.md
pygments: true
tagline: Site Tagline
production_url: http://username.github.io
JB:
  version: 0.3.0
  BASE_PATH: false
  ASSET_PATH: false
  archive_path: "/archive.html"
  categories_path: "/categories.html"
  tags_path: "/tags.html"
  atom_path: "/atom.xml"
  rss_path: "/rss.xml"
  comments:
    provider: disqus
    disqus:
      short_name: jekyllbootstrap
    livefyre:
      site_id: 123
    intensedebate:
      account: 123abc
    facebook:
      appid: 123
      num_posts: 5
      width: 580
      colorscheme: light
  analytics:
    provider: google
    google:
      tracking_id: UA-123-12
    getclicky:
      site_id: 
    mixpanel:
      token: _MIXPANEL_TOKEN_
    piwik:
      baseURL: myserver.tld/piwik
      idsite: 1
  sharing:
    provider: false
