---
title: My Resume
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://harssh.github.io
baseurl: "/"
description: Harssh S Shrivastava Full Stack Ruby On Rails developer.
theme_skin: blue
chrome_mobile_color:
analytics: UA-83979
sass:
  sass_dir: _sass
  style: compressed
compress-site: true
encoding: utf-8
compress_html:
  clippings: all
  ignore:
    envs: development
port: 4000
host: 0.0.0.0
safe: false
sidebar:
    about: True # set to False or comment line if you want to remove the "how to use?" in the sidebar
    education: True # set to False if you want education in main section instead of in sidebar

    # Profile information
    name: Harssh S Shrivastava
    tagline: Full Stack Developer/ Ruby ON Rails Engineer
    avatar: profile.jpeg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

    # Sidebar links
    email: harssh122@gmail.com
    phone: 763 283 8442
    website: github.com/harssh #do not add http://
    linkedin: harssh
    github: harssh
    gitlab:
    bitbucket:
    twitter: '@IamStackDev'
    stack-overflow: 1863010/magnum # Number/Username, e.g. 123456/alandoe
    codewars:
    goodreads: # Number-Username, e.g. 123456-alandoe

    languages:
      - idiom: English
        level: Professional


career-profile:
    title: Career Profile
    summary: |
      Summarise your career here lorem ipsum dolor sit amet, consectetuer
      adipiscing elit. You can [download this free resume/CV template here]().
      Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque
      penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      Donec quam felis, ultricies nec, pellentesque eu.

      Second paragraph if required.

education:
    - degree: BE in Information Technology
      university: University of Pune
      time: 2008 - 2012
      details: |
        Describe your study here lorem ipsum dolor sit amet, consectetuer
        adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum
        sociis natoque penatibus et magnis dis parturient montes, nascetur
        ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu,
        pretium quis, sem.

          - Bullet point
          - Bullet point

experiences:
    - role: Lead Developer
      time: 2015 - Present
      company: Startup Hubs, San Francisco
      details: |
        Describe your role here lorem ipsum dolor sit amet, consectetuer
        adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
        Cum sociis natoque penatibus et magnis dis parturient montes,
        nascetur ridiculus mus. Donec quam felis, ultricies nec,
        pellentesque eu, pretium quis, sem. Nulla consequat massa quis
        enim. Donec pede justo. Sed ut perspiciatis unde omnis iste natus
        error sit voluptatem accusantium doloremque laudantium, totam rem
        aperiam, eaque ipsa quae ab illo inventore veritatis et quasi
        architecto beatae vitae dicta sunt explicabo.

          - Bullet point
          - Bullet point

    - role: Senior Software Engineer
      time: 2014 - 2015
      company: Google, London
      details: |
        Describe your role here lorem ipsum dolor sit amet, consectetuer
        adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
        Cum sociis natoque penatibus et magnis dis parturient montes,
        nascetur ridiculus mus. Donec quam felis, ultricies nec,
        pellentesque eu, pretium quis, sem.

          - Bullet point
          - Bullet point

    - role: UI Developer
      time: 2012 - 2014
      company: Amazon, London
      details: |
        Describe your role here lorem ipsum dolor sit amet, consectetuer
        adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
        Cum sociis natoque penatibus et magnis dis parturient montes,
        nascetur ridiculus mus. Donec quam felis, ultricies nec,
        pellentesque eu, pretium quis, sem.

          - Bullet point
          - Bullet point

projects:
    title: Projects
    intro: >
      You can list your side projects or open source libraries in this
      section. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Vestibulum et ligula in nunc bibendum fringilla a eu lectus.

    assignments:
      - title: Velocity
        link: "#hook"
        tagline: "A responsive website template designed to help startups promote, market and sell their products."

      - title: DevStudio
        link: "#"
        tagline: "A responsive website template designed to help web developers/designers market their services."

      - title: Tempo
        link: "#"
        tagline: "A responsive website template designed to help startups promote their products or services and to attract users &amp; investors"

      - title: Atom
        link: "#"
        tagline: "A comprehensive website template solution for startups/developers to market their mobile apps."

      - title: Delta
        link: "#"
        tagline: "A responsive Bootstrap one page theme designed to help app developers promote their mobile apps"

publications:
    title: Publications
    intro: |
      You can list your publications in this section. Lorem ipsum dolor sit
      amet, consectetur adipiscing elit. Vestibulum et ligula in nunc
      bibendum fringilla a eu lectus.

    papers:
      - title: The Art of Computer Programming
        authors: Donald E. Knuth
        conference: Addison-Wesley, 1968

      - title: "Genetic Programming III: Darwinian Invention &amp; Problem Solving"
        authors: Koza, J.R., Andre, D., Bennett, F.H., Keane, M.A.
        conference: "Morgan Kaufmann Publishers Inc., San Francisco, CA, USA, 1st edn. (1999)"

      - title: A syntax directed compiler for Algol 60
        authors: Edgar T. Irons
        conference: "Comm. ACM 4 (1961), 51–55"

skills:
    title: Skills &amp; Proficiency

    toolset:
      - name: Python & Django
        level: 98%

      - name: Javascript & jQuery
        level: 98%

      - name: Angular
        level: 98%

      - name: HTML5 & CSS
        level: 95%

      - name: Ruby on Rails
        level: 85%

      - name: Sketch & Photoshop
        level: 60%

footer: >
    Designed by <a href="http://themes.3rdwavemedia.com" target="_blank" rel="nofollow">Xiaoying Riley</a>
